In [1]:
import numpy as np
import sys

In [96]:
a = np.array([[1.8, 2.0, 5.6, 6.7],[1.5, 2.0, 5.6, 6.7]], dtype="float32")

In [97]:
print(a)

[[1.8 2.  5.6 6.7]
 [1.5 2.  5.6 6.7]]


In [98]:
a.size

8

In [99]:
a.itemsize

4

In [116]:
b = np.array([[1,3], [2,4]])

In [117]:
b

array([[1, 3],
       [2, 4]])

In [118]:
c = np.full_like(b, 6)

In [119]:
c

array([[6, 6],
       [6, 6]])

In [130]:
a = np.array([1, 2])

In [134]:
np.random.random_sample(a.shape)

array([0.21934483, 0.1232815 ])

In [135]:
a = np.arange(8).reshape((2,2,2))

In [136]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [137]:
a.trace()

array([6, 8])

In [138]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
b = np.array([[1, 2, 4], [1, 2, 4], [1, 2, 4]])
b

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [7]:
import numpy as np

In [8]:
np.trace(b)

7

In [13]:
a = np.arange(24).reshape((2,2,2,3))
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [11]:
np.trace(a)

array([[18, 20, 22],
       [24, 26, 28]])

In [17]:
a = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])

In [18]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
np.trace(a)

5

In [37]:
a = np.array([[1,2, 5],[3,4, 6],[2,4, 2]])

In [38]:
a

array([[1, 2, 5],
       [3, 4, 6],
       [2, 4, 2]])

In [39]:
a.diagonal()

array([1, 4, 2])

In [40]:
a.diagonal(1)

array([2, 6])

In [42]:
a.diagonal(-1)

array([3, 4])

In [43]:
a

array([[1, 2, 5],
       [3, 4, 6],
       [2, 4, 2]])

In [44]:
np.fliplr(a)

array([[5, 2, 1],
       [6, 4, 3],
       [2, 4, 2]])

In [45]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)

In [46]:
a

array([[ 0.2017285 +0.33244751j,  0.60172942-0.09613733j,
         1.64935076-1.09763038j,  0.51684786+0.32929943j,
        -0.31391792-2.29194825j, -0.88974493+0.53809363j],
       [-0.93650312-0.57000826j,  1.14536062+0.35406577j,
        -0.08581609+1.16328547j, -0.25623813+0.66454227j,
         0.06043919+1.29642251j, -1.26060422+1.91393676j],
       [ 0.51479459-0.30908913j, -0.21800032-0.92914924j,
         0.75798387-0.07962645j, -0.44523031+0.28678752j,
        -0.32289625+1.18212391j,  1.38261097-1.2681647j ],
       [ 1.34137734+0.11522664j, -1.71489565+2.41092999j,
        -0.39593355+0.99040231j,  1.32146878+0.29793646j,
         0.28061219-0.39887401j,  1.50329037+0.94259617j],
       [ 0.30728087+0.25235488j, -1.09584906-0.83813115j,
        -0.02976567-0.21124474j, -0.57198115+0.51826284j,
         0.83798352+0.61186959j, -0.34255106-0.09765705j],
       [-0.50818678-1.90480285j, -0.85114564-0.55890551j,
        -1.62448105-2.55950996j,  0.87971305-0.06781445j,
        -

In [47]:
U, s, V = np.linalg.svd(a, full_matrices=True)

In [48]:
U.shape, V.shape, s.shape

((9, 9), (6, 6), (6,))

In [49]:
S = np.zeros((9, 6), dtype=complex)

In [50]:
S

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [51]:
S[:6, :6] = np.diag(s)

In [52]:
S

array([[5.6696624 +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 5.23476841+0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 4.27405908+0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 3.37849977+0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        2.32030861+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 1.07465771+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 

In [53]:
np.allclose(a, np.dot(U, np.dot(S, V)))

True

In [54]:
U

array([[-2.41682049e-01+0.16403349j,  2.50384551e-01+0.367476j  ,
         5.32021423e-02+0.1168316j , -2.57441276e-01-0.35005314j,
         3.10135031e-01-0.05950838j,  2.43958378e-01+0.16969328j,
        -1.60367441e-01-0.09905082j,  3.28104752e-01-0.11660189j,
        -2.46486628e-01+0.32571278j],
       [ 3.53033516e-02-0.10660178j, -1.99706452e-01+0.21544306j,
         3.73360893e-01-0.24030365j, -1.15051583e-01+0.59541151j,
         1.93143612e-01+0.31867155j,  2.82906221e-01+0.17290576j,
         1.06615915e-01+0.00994565j,  1.57650691e-01+0.12856605j,
         1.01034375e-01+0.15604582j],
       [ 8.26909371e-02-0.10146277j,  1.22206638e-01-0.10941132j,
        -3.96180654e-01+0.24177652j,  2.36431616e-01+0.27148225j,
        -2.30613881e-01-0.08489057j,  8.91772806e-02+0.31902337j,
        -2.03320355e-01-0.29441735j,  3.14001660e-02+0.24960057j,
         7.42943158e-02+0.49396379j],
       [-4.31247308e-01-0.00783698j, -1.55902974e-01-0.36888507j,
        -2.46222468e-01-0.49

In [55]:
s

array([5.6696624 , 5.23476841, 4.27405908, 3.37849977, 2.32030861,
       1.07465771])

In [56]:
V

array([[-0.32018386+0.j        ,  0.09420971-0.47048776j,
        -0.30318007+0.16670218j, -0.39024032-0.51005801j,
        -0.28826949+0.17414262j, -0.03453748-0.14309387j],
       [ 0.18827551+0.j        , -0.22797473-0.58670798j,
         0.16881481-0.54110007j, -0.06678948+0.11615474j,
        -0.22524736-0.17500104j,  0.19428579+0.33166913j],
       [-0.20211414+0.j        ,  0.00760303-0.07898j   ,
        -0.45653203-0.24831052j,  0.16071258+0.19394529j,
         0.11144541+0.07587874j, -0.71275034+0.30518945j],
       [-0.26077482+0.j        ,  0.0404252 -0.42223988j,
        -0.02060897-0.0661648j ,  0.29725555+0.04111842j,
         0.69865235+0.22234628j,  0.28392554-0.19762338j],
       [-0.81874646+0.j        ,  0.02748407+0.21381148j,
         0.10270949-0.14056756j, -0.17431532+0.25565614j,
        -0.09452964-0.2972165j ,  0.22085966+0.10524566j],
       [-0.28781111+0.j        , -0.37409095-0.03059313j,
         0.49480338+0.09478139j,  0.50413215-0.25731412j,
        -

In [150]:
w, v = LA.eig(np.diag((1, 2, 3)))

In [58]:
from numpy import linalg as LA

In [59]:
w, v = LA.eig(np.diag((1, 2, 3)))

In [60]:
w

array([1., 2., 3.])

In [61]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
w, v = LA.eig(np.array([[1, -1], [1, 1]]))

In [63]:
w

array([1.+1.j, 1.-1.j])

In [64]:
v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

In [154]:
a = np.array([[1., 2.], [3., 4.]])

In [155]:
from numpy.linalg import inv
ainv = inv(a)

In [67]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [69]:
np.sum(a)

21

In [70]:
np.sum(a, axis=0)

array([5, 7, 9])

In [71]:
np.sum(a, axis=1)

array([ 6, 15])

In [72]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [73]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [77]:
np.array(list(filter(lambda x: x%2==0, np.arange(2,100))))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [78]:
np.ones((1,5))*10

array([[10., 10., 10., 10., 10.]])

In [80]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
np.random.randn((25)).reshape((5,5))

array([[ 0.598454  , -0.85594921, -0.96285293,  0.49730407,  1.84790455],
       [-0.91642925,  0.46916225,  0.81704503,  0.21989438, -0.2126814 ],
       [ 0.27488514,  0.12717807, -0.95459805, -0.56511551, -1.04451198],
       [ 0.31275146,  1.95792735,  1.39276278,  2.12277628,  0.32500381],
       [-1.18708428,  0.99313826, -1.68169536, -0.66877369,  0.65320765]])

In [148]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [147]:
np.random.rand() * 5 

1.477195467986585

In [106]:
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [107]:
arr>40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [113]:
a = arr[arr>40]
a.reshape(6,10)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [149]:
arr[6:, 4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [118]:
arr[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [119]:
arr[0:3, 1]

array([ 2, 12, 22])

In [120]:
arr[0:3, 1].reshape(3,1)

array([[ 2],
       [12],
       [22]])

In [121]:
arr[:, -1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [122]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [123]:
arr1

array([[2, 3, 0],
       [3, 4, 2],
       [1, 3, 3]])

In [124]:
arr2

array([[2, 3, 2],
       [2, 2, 0],
       [0, 2, 1]])

In [125]:
arr1 + arr2

array([[4, 6, 2],
       [5, 6, 2],
       [1, 5, 4]])

In [126]:
arr1 * arr2

array([[4, 9, 0],
       [6, 8, 0],
       [0, 6, 3]])

In [135]:
arr1.size

9

In [136]:
np.sum(arr1)/ arr1.size

2.3333333333333335

In [137]:
np.sum(arr1)

21

In [141]:
np.random.rand(9) * 5

array([4.37628458, 1.84228426, 4.704749  , 2.43542195, 2.06306498,
       2.40094217, 4.22058968, 3.89306069, 3.17284812])